var languagesData = {
  en: {
    announcements: {
      noteIsSaved: "Note saved",
      BinEmptied: "The bin has been emptied",
      CategoryExists: "A category with this name already exists",
      CategoryRenamed: "Category name has been changed",
      NoteDeleted: "Note has been deleted",
      noteRestored: "Note has been restored",
      restoredAllNotes: "All notes has been restored",
      categoryChanged: "Category has been changed",
      categoryDeletedFromNote: "Category has been removed from the note",
      noCategoryToChoose: "No category to choose",
      dataLoaded: "Data loaded",
      parsingError: "Parsing error",
      unableToLoad: "Unable to load",
    },
    text: {
      bin: "Bin",
      settings: "Settings",
      Note: "Note",
      ApplicationTitle: "Notebook",
      allNotes: "All Notes",
      categories: "Categories",
      withoutCategory: "Without Category",
      editCategory: "Edit Category",
      newNote: "New",
      withoutTitle: "Without title",
      changeNameOfCategory: "Change Category Name",
      actionForNote: "Choose an action for this note",
      deleteNote: "Delete",
      searchInNote: "Search",
      categorize: "Categorize",
      restoreNote: "Restore Note",
      restoreAllNotes: "Restore All Notes",
      deletePermanentlyNote: "Delete Note Permanently",
      emptyTheBin: "Empty the Bin",
      lastSave: "last saved",
      selectLanguage: "Select language",
      darkMode: "Dark Mode",
      chooseCategory: "Choose category",
      deleteCategory: "Delete category",
      importData: "import data",
      eksportData: "export data",
      selectFile: "select file",
      export: "export",
    },
    language: {
      en: "English",
      pl: "Polish",
      zh: "Chinese",
      es: "Spanish",
      de: "German",
      ru: "Russian",
      fr: "French",
    },
    placeholder: {
      nameOfNewCategory: "Name of the new category...",
    },
    button: {
      addNewCategory: "ADD",
      cancel: "Cancel",
      confirmation: "OK",
      saveNote: "SAVE",
    },
  },
  pl: {
    announcements: {
      noteIsSaved: "Zapisano notatkę",
      BinEmptied: "Kosz został opróżniony",
      CategoryExists: "Kategoria z tą nazwą istnieje",
      CategoryRenamed: "Nazwa kategorii została zmieniona",
      NoteDeleted: "Notatka została usunięta",
      noteRestored: "Notatka została przywrócona",
      restoredAllNotes: "Wszystkie notatki zostały przywrócone",
      categoryChanged: "Kategoria została zmieniona",
      categoryDeletedFromNote: "Kategoria została usunięta z notatki",
      noCategoryToChoose: "Brak kategorii do wybrania",
      dataLoaded: "Wczytano dane",
      parsingError: "Błąd parsowania",
      unableToLoad: "Nie udało się wczytać",
    },
    text: {
      bin: "Kosz",
      settings: "Ustawienia",
      Note: "Notatka",
      ApplicationTitle: "Notatnik",
      allNotes: "Wszystkie notatki",
      categories: "Kategorie",
      withoutCategory: "Bez kategorii",
      editCategory: "Edytuj Kategorie",
      newNote: "Nowa",
      withoutTitle: "Bez tytułu",
      changeNameOfCategory: "Zmień nazwę kategorii",
      actionForNote: "Wybierz akcję dla tej notatki",
      deleteNote: "Usuń",
      searchInNote: "Szukaj",
      categorize: "Kategoryzuj",
      restoreNote: "Przywróć notatkę",
      restoreAllNotes: "Przywróć wszystkie notatki",
      deletePermanentlyNote: "Usuń trwale notatkę",
      emptyTheBin: "Opróżnij kosz",
      lastSave: "Ostatni zapis",
      selectLanguage: "Wybierz język",
      darkMode: "Tryb ciemny",
      chooseCategory: "Wybierz kategorię",
      deleteCategory: "Usuń kategorię",
      importData: "importuj dane",
      eksportData: "exportuj dane",
      selectFile: "wybierz plik",
      export: "exportuj",
    },
    language: {
      en: "Angielski",
      pl: "Polski",
      zh: "chiński",
      es: "Hiszpański",
      de: "Niemiecki",
      ru: "Rosyjski",
      fr: "Francuski",
    },
    placeholder: {
      nameOfNewCategory: "Nazwa nowej kategorii...",
    },
    button: {
      addNewCategory: "DODAJ",
      cancel: "ANULUJ",
      confirmation: "OK",
      saveNote: "ZAPISZ",
    },
  },
  zh: {
    announcements: {
      noteIsSaved: "笔记已保存",
      BinEmptied: "回收站已清空",
      CategoryExists: "该名称的类别已存在",
      CategoryRenamed: "类别名称已更改",
      NoteDeleted: "笔记已删除",
      noteRestored: "笔记已恢复",
      restoredAllNotes: "所有笔记已恢复",
      categoryChanged: "类别已更改",
      categoryDeletedFromNote: "类别已从笔记中删除",
      noCategoryToChoose: "没有可选择的类别",
      dataLoaded: "数据已加载",
      parsingError: "解析错误",
      unableToLoad: "无法加载",
    },
    text: {
      bin: "回收站",
      settings: "设置",
      Note: "笔记",
      ApplicationTitle: "笔记本",
      allNotes: "所有笔记",
      categories: "类别",
      withoutCategory: "无类别",
      editCategory: "编辑类别",
      newNote: "新建",
      withoutTitle: "无标题",
      changeNameOfCategory: "更改类别名称",
      actionForNote: "为此笔记选择操作",
      deleteNote: "删除",
      searchInNote: "搜索",
      categorize: "分类",
      restoreNote: "恢复笔记",
      restoreAllNotes: "恢复所有笔记",
      deletePermanentlyNote: "永久删除笔记",
      emptyTheBin: "清空回收站",
      lastSave: "上次保存",
      selectLanguage: "选择语言",
      darkMode: "暗黑模式",
      chooseCategory: "选择类别",
      deleteCategory: "删除类别",
      importData: "导入数据",
      eksportData: "导出数据",
      selectFile: "选择文件",
      export: "导出",
    },
    language: {
      en: "英语",
      pl: "波兰语",
      zh: "中文",
      es: "西班牙语",
      de: "德语",
      ru: "俄语",
      fr: "法语",
    },
    placeholder: {
      nameOfNewCategory: "新类别名称...",
    },
    button: {
      addNewCategory: "添加",
      cancel: "取消",
      confirmation: "确定",
      saveNote: "保存",
    },
  },
  es: {
    announcements: {
      noteIsSaved: "Nota guardada",
      BinEmptied: "La papelera ha sido vaciada",
      CategoryExists: "Ya existe una categoría con este nombre",
      CategoryRenamed: "El nombre de la categoría ha sido cambiado",
      NoteDeleted: "La nota ha sido eliminada",
      noteRestored: "La nota ha sido restaurada",
      restoredAllNotes: "Todas las notas han sido restauradas",
      categoryChanged: "La categoría ha sido cambiada",
      categoryDeletedFromNote: "La categoría se ha eliminado de la nota",
      noCategoryToChoose: "No hay categorías para elegir",
      dataLoaded: "Datos cargados",
      parsingError: "Error de análisis",
      unableToLoad: "No se pudo cargar",
    },
    text: {
      bin: "Papelera",
      settings: "Configuración",
      Note: "Nota",
      ApplicationTitle: "Bloc de notas",
      allNotes: "Todas las notas",
      categories: "Categorías",
      withoutCategory: "Sin categoría",
      editCategory: "Editar categoría",
      newNote: "Nueva",
      withoutTitle: "Sin título",
      changeNameOfCategory: "Cambiar nombre de la categoría",
      actionForNote: "Elige una acción para esta nota",
      deleteNote: "Eliminar",
      searchInNote: "Buscar",
      categorize: "Categorizar",
      restoreNote: "Restaurar nota",
      restoreAllNotes: "Restaurar todas las notas",
      deletePermanentlyNote: "Eliminar nota permanentemente",
      emptyTheBin: "Vaciar la papelera",
      lastSave: "último guardado",
      selectLanguage: "Seleccionar idioma",
      darkMode: "Modo oscuro",
      chooseCategory: "Elige categoría",
      deleteCategory: "Eliminar categoría",
      importData: "importar datos",
      eksportData: "exportar datos",
      selectFile: "seleccionar archivo",
      export: "exportar",
    },
    language: {
      en: "Inglés",
      pl: "Polaco",
      zh: "Chino",
      es: "Español",
      de: "Alemán",
      ru: "Ruso",
      fr: "Francés",
    },
    placeholder: {
      nameOfNewCategory: "Nombre de la nueva categoría...",
    },
    button: {
      addNewCategory: "AÑADIR",
      cancel: "Cancelar",
      confirmation: "OK",
      saveNote: "GUARDAR",
    },
  },
  de: {
    announcements: {
      noteIsSaved: "Notiz gespeichert",
      BinEmptied: "Papierkorb wurde geleert",
      CategoryExists: "Eine Kategorie mit diesem Namen existiert bereits",
      CategoryRenamed: "Kategoriename wurde geändert",
      NoteDeleted: "Notiz wurde gelöscht",
      noteRestored: "Notiz wurde wiederhergestellt",
      restoredAllNotes: "Alle Notizen wurden wiederhergestellt",
      categoryChanged: "Kategorie wurde geändert",
      categoryDeletedFromNote: "Kategorie wurde aus der Notiz entfernt",
      noCategoryToChoose: "Keine Kategorie zum Auswählen",
      dataLoaded: "Daten geladen",
      parsingError: "Parsing-Fehler",
      unableToLoad: "Laden nicht möglich",
    },
    text: {
      bin: "Papierkorb",
      settings: "Einstellungen",
      Note: "Notiz",
      ApplicationTitle: "Notizbuch",
      allNotes: "Alle Notizen",
      categories: "Kategorien",
      withoutCategory: "Ohne Kategorie",
      editCategory: "Kategorie bearbeiten",
      newNote: "Neu",
      withoutTitle: "Ohne Titel",
      changeNameOfCategory: "Kategorienamen ändern",
      actionForNote: "Aktion für diese Notiz auswählen",
      deleteNote: "Löschen",
      searchInNote: "Suchen",
      categorize: "Kategorisieren",
      restoreNote: "Notiz wiederherstellen",
      restoreAllNotes: "Alle Notizen wiederherstellen",
      deletePermanentlyNote: "Notiz dauerhaft löschen",
      emptyTheBin: "Papierkorb leeren",
      lastSave: "zuletzt gespeichert",
      selectLanguage: "Sprache auswählen",
      darkMode: "Dunkelmodus",
      chooseCategory: "Kategorie wählen",
      deleteCategory: "Kategorie löschen",
      importData: "Daten importieren",
      eksportData: "Daten exportieren",
      selectFile: "Datei auswählen",
      export: "exportieren",
    },
    language: {
      en: "Englisch",
      pl: "Polnisch",
      zh: "Chinesisch",
      es: "Spanisch",
      de: "Deutsch",
      ru: "Russisch",
      fr: "Französisch",
    },
    placeholder: {
      nameOfNewCategory: "Name der neuen Kategorie...",
    },
    button: {
      addNewCategory: "HINZUFÜGEN",
      cancel: "Abbrechen",
      confirmation: "OK",
      saveNote: "SPEICHERN",
    },
  },
  ru: {
    announcements: {
      noteIsSaved: "Заметка сохранена",
      BinEmptied: "Корзина очищена",
      CategoryExists: "Категория с таким именем уже существует",
      CategoryRenamed: "Имя категории изменено",
      NoteDeleted: "Заметка удалена",
      noteRestored: "Заметка восстановлена",
      restoredAllNotes: "Все заметки восстановлены",
      categoryChanged: "Категория была изменена",
      categoryDeletedFromNote: "Категория была удалена из заметки",
      noCategoryToChoose: "Нет категории для выбора",
      dataLoaded: "Данные загружены",
      parsingError: "Ошибка разбора",
      unableToLoad: "Не удалось загрузить",
    },
    text: {
      bin: "Корзина",
      settings: "Настройки",
      Note: "Заметка",
      ApplicationTitle: "Блокнот",
      allNotes: "Все заметки",
      categories: "Категории",
      withoutCategory: "Без категории",
      editCategory: "Редактировать категорию",
      newNote: "Новая",
      withoutTitle: "Без названия",
      changeNameOfCategory: "Изменить название категории",
      actionForNote: "Выберите действие для этой заметки",
      deleteNote: "Удалить",
      searchInNote: "Поиск",
      categorize: "Категоризировать",
      restoreNote: "Восстановить заметку",
      restoreAllNotes: "Восстановить все заметки",
      deletePermanentlyNote: "Удалить заметку навсегда",
      emptyTheBin: "Очистить корзину",
      lastSave: "последнее сохранение",
      selectLanguage: "Выбрать язык",
      darkMode: "Тёмный режим",
      chooseCategory: "Выберите категорию",
      deleteCategory: "Удалить категорию",
      importData: "импортировать данные",
      eksportData: "экспортировать данные",
      selectFile: "выбрать файл",
      export: "экспорт",
    },
    language: {
      en: "Английский",
      pl: "Польский",
      zh: "Китайский",
      es: "Испанский",
      de: "Немецкий",
      ru: "Русский",
      fr: "Французский",
    },
    placeholder: {
      nameOfNewCategory: "Название новой категории...",
    },
    button: {
      addNewCategory: "ДОБАВИТЬ",
      cancel: "Отмена",
      confirmation: "ОК",
      saveNote: "СОХРАНИТЬ",
    },
  },
  fr: {
    announcements: {
      noteIsSaved: "Note enregistrée",
      BinEmptied: "La corbeille a été vidée",
      CategoryExists: "Une catégorie avec ce nom existe déjà",
      CategoryRenamed: "Le nom de la catégorie a été modifié",
      NoteDeleted: "La note a été supprimée",
      noteRestored: "La note a été restaurée",
      restoredAllNotes: "Toutes les notes ont été restaurées",
      categoryChanged: "La catégorie a été modifiée",
      categoryDeletedFromNote: "La catégorie a été supprimée de la note",
      noCategoryToChoose: "Aucune catégorie à sélectionner",
      dataLoaded: "Données chargées",
      parsingError: "Erreur d'analyse",
      unableToLoad: "Impossible de charger",
    },
    text: {
      bin: "Corbeille",
      settings: "Paramètres",
      Note: "Note",
      ApplicationTitle: "Carnet de notes",
      allNotes: "Toutes les notes",
      categories: "Catégories",
      withoutCategory: "Sans catégorie",
      editCategory: "Modifier la catégorie",
      newNote: "Nouveau",
      withoutTitle: "Sans titre",
      changeNameOfCategory: "Changer le nom de la catégorie",
      actionForNote: "Choisissez une action pour cette note",
      deleteNote: "Supprimer",
      searchInNote: "Rechercher",
      categorize: "Catégoriser",
      restoreNote: "Restaurer la note",
      restoreAllNotes: "Restaurer toutes les notes",
      deletePermanentlyNote: "Supprimer la note définitivement",
      emptyTheBin: "Vider la corbeille",
      lastSave: "dernière sauvegarde",
      selectLanguage: "Choisir la langue",
      darkMode: "Mode sombre",
      chooseCategory: "Choisir une catégorie",
      deleteCategory: "Supprimer la catégorie",
      importData: "importer des données",
      eksportData: "exporter des données",
      selectFile: "sélectionner un fichier",
      export: "exporter",
    },
    language: {
      en: "Anglais",
      pl: "Polonais",
      zh: "Chinois",
      es: "Espagnol",
      de: "Allemand",
      ru: "Russe",
      fr: "Français",
    },
    placeholder: {
      nameOfNewCategory: "Nom de la nouvelle catégorie...",
    },
    button: {
      addNewCategory: "AJOUTER",
      cancel: "Annuler",
      confirmation: "OK",
      saveNote: "ENREGISTRER",
    },
  },
};
